---

- name: Upgrade all packages
  yum: name=* state=latest

- name: Install required packages
  yum: name={{ item }} state=latest
  with_items:
    - unzip
    - tmux
  tags: packages

- include: install-java.yml
- include: create-minecraft-user.yml
- include: create-minecraft-home.yml
- include: copy-minecraft-eula.yml
- include: create-minecraft-systemd-conf.yml
- include: firewalld.yml